### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by DecampsRenan** [BearStudio/start-ui#69]
When running `yarn test` on bare-bones start-ui project, the test fail.

<img width="1093" alt="CleanShot 2021-07-08 at 09 45 53@2x" src="https://user-images.githubusercontent.com/7521065/124883445-9c65ac80-dfd1-11eb-8198-931a4947c35b.png">

```
 FAIL  src/app/App.spec.tsx
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: window is not defined

      2 | import mediaQuery from 'css-mediaquery';
      3 |
    > 4 | window.scrollTo = () => undefined;
        | ^
      5 |
      6 | global.matchMedia =
      7 |   global.matchMedia ||

      at Object.<anonymous> (src/test/setup.ts:4:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:347:13)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.437 s
Ran all test suites.

Watch Usage: Press w to show more.
```

**Comment by yoannfleurydev** [comment]
Adding this line should fix the issue.

```ts
  testEnvironment: 'jsdom',
```

![bitmoji](https://sdk.bitmoji.com/render/panel/0af50f50-76b8-413b-b6bb-616208e086ef-28509fbe-5dd0-4c1e-9b9f-5043673dc433-v1.png?transparent=1&palette=1&width=246)
